import { z } from 'zod';
export declare const BiTemporalAuditFact: z.ZodObject<{
    entityId: z.ZodString;
    attribute: z.ZodString;
    value: z.ZodUnknown;
    validFrom: z.ZodString;
    validTo: z.ZodNullable<z.ZodString>;
    txFrom: z.ZodString;
    txTo: z.ZodNullable<z.ZodString>;
    source: z.ZodOptional<z.ZodString>;
    evidenceId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    entityId: string;
    attribute: string;
    validFrom: string;
    validTo: string | null;
    txFrom: string;
    txTo: string | null;
    value?: unknown;
    source?: string | undefined;
    evidenceId?: string | undefined;
}, {
    entityId: string;
    attribute: string;
    validFrom: string;
    validTo: string | null;
    txFrom: string;
    txTo: string | null;
    value?: unknown;
    source?: string | undefined;
    evidenceId?: string | undefined;
}>;
export declare const BiTemporalAuditEdge: z.ZodObject<{
    subjectId: z.ZodString;
    predicate: z.ZodString;
    objectId: z.ZodString;
    validFrom: z.ZodString;
    validTo: z.ZodNullable<z.ZodString>;
    txFrom: z.ZodString;
    txTo: z.ZodNullable<z.ZodString>;
    source: z.ZodOptional<z.ZodString>;
    evidenceId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    validFrom: string;
    validTo: string | null;
    txFrom: string;
    txTo: string | null;
    subjectId: string;
    predicate: string;
    objectId: string;
    source?: string | undefined;
    evidenceId?: string | undefined;
}, {
    validFrom: string;
    validTo: string | null;
    txFrom: string;
    txTo: string | null;
    subjectId: string;
    predicate: string;
    objectId: string;
    source?: string | undefined;
    evidenceId?: string | undefined;
}>;
export type BiTemporalAuditFactType = z.infer<typeof BiTemporalAuditFact>;
export type BiTemporalAuditEdgeType = z.infer<typeof BiTemporalAuditEdge>;
export type BiTemporalRecord = BiTemporalAuditFactType | BiTemporalAuditEdgeType;
export declare function intervalContains(from: string, to: string | null, at: string): boolean;
export declare function intervalsOverlap(leftFrom: string, leftTo: string | null, rightFrom: string, rightTo: string | null): boolean;
export declare function isKnownAt(record: BiTemporalRecord, txAt: string): boolean;
export declare function isValidAt(record: BiTemporalRecord, validAt: string): boolean;
export declare function isVisibleAt(record: BiTemporalRecord, validAt: string, txAt: string): boolean;
export declare function validIntervalsOverlap(left: Pick<BiTemporalRecord, 'validFrom' | 'validTo'>, right: Pick<BiTemporalRecord, 'validFrom' | 'validTo'>): boolean;
